
spring.main.allow-bean-definition-overriding=true
# Mail verification code's expiration time
verification.code.expiration=15

spring.main.allow-circular-references=true
sendgrid.secret.key=
spring.config.import=classpath:dynamic-configs.properties

#transactions.receipts.path=/apps/atm-app/receipts
transactions.receipts.path=/apps/atm/receipts
#static.resources.receipts.path=/D:/files/receipts/
static.resources.receipts.path=/apps/atm/receipts/

# Port
server.port=30
server.local.host=127.0.0.1
server.remote.host=

# Oauth GitHub
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


# White label
server.error.whitelabel.enabled=true
server.servlet.session.cookie.same-site=NONE
server.servlet.session.cookie.secure=true

# base url
# server.servlet.context-path=/base_url

# Log
logging.file.name=./log/blog.log

# OFF > FATAL > ERROR > WARN > INFO >DEBUG > TRACE
logging.level.root=INFO
## Database config
logging.level.org.springframework.jdbc.core = TRACE
spring.jpa.properties.hibernate.format_sql =true
spring.jpa.properties.hibernate.show_sql=true
spring.sql.init.platform=mysql
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# spring.jpa.hibernate.ddl-auto = create
spring.jpa.hibernate.ddl-auto = update
#spring.datasource.url=jdbc:mysql://localhost:3306/atm_test?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=12345
spring.jpa.show-sql=true
# During tests: set redis host to localhost
spring.data.redis.host=redis
spring.data.redis.port=6379
